registryList:
  - "docker.arvancloud.ir"
  - "focker.ir"
  - "registry.docker.ir"
  - "docker.host:5000"
  - "docker.iranserver.com"
  - "docker.haiocloud.com"
  - "registry.registryhub.ir"
  - "docker-mirror.kubarcloud.com"
  - "hub.hamdocker.ir"
  - "docker.mobinhost.com"
  - "docker.kernel.ir"
  - "mirrors.pardisco.co"
  - "hub.atlantiscloud.ir"
  - "docker.chabokan.net"
